chore: remove uritemplate for exposecontroller
it seems to conflict with jenkins x templating, 
```

error: generating values.yaml for tree from /tmp/**-helm-apply-289789879/env: failed to render template of file /tmp/**-helm-apply-289789879/env/values.tmpl.yaml: failed to execute Secrets template: /tmp/**-helm-apply-289789879/env/values.tmpl.yaml: template: values.tmpl.yaml:20:20: executing "values.tmpl.yaml" at <.Service>: map has no entry for key "Service"

```